### ISSUE TITLE
Some "unrecognized property" `microprofile(unknown)`

### ISSUE THREAD

**Issue by gian1200** [xorye/vscode-quarkus#734]
Warning: 
> Unrecognized property 'quarkus.datasource.db-kind', it is not referenced in any Java files `microprofile(unknown)`

There are some properties that are wrongly flagged. Some of them used to be correctly identified in Quarkus 2, not anymore in Quarkus 3.

### Used to work
 (possibly related to: https://github.com/quarkusio/quarkus/issues/32943)

- quarkus.datasource.db-kind
- quarkus.datasource.credentials-provider

![image](https://github.com/redhat-developer/vscode-quarkus/assets/405347/9ca8724e-ba1c-4fb0-aa38-c8613783a0b9)

### New ones

- Any cache defined with `@CacheResult`. E.g. `quarkus.cache.caffeine."name-redacted".expire-after-write` (from `quarkus-cache`)

![image](https://github.com/redhat-developer/vscode-quarkus/assets/405347/704459db-4e47-4809-9c84-87b14626fc63)
![image](https://github.com/redhat-developer/vscode-quarkus/assets/405347/81f9d4a0-308c-4ba3-af2d-4164be7f239d)

- Any property referenced inside `@ClientFormParam`

![image](https://github.com/redhat-developer/vscode-quarkus/assets/405347/586f283d-d93c-4af0-a568-f88cf7d7eb1b)
![image](https://github.com/redhat-developer/vscode-quarkus/assets/405347/3f07555a-7ad7-40f8-af2e-05a7ee9c2e8e)

**Comment by angelozerr** [comment]
The db-kind property is defined https://github.com/quarkusio/quarkus/blob/0109749726be6e5aafd2943f620a64be2b1220fe/extensions/datasource/runtime/src/main/java/io/quarkus/datasource/runtime/DataSourceBuildTimeConfig.java#L17 but I have not found where this interface is used to compute the property starting with quatkus.datasource

@ia3andy have you some idea how this property is computed?

**Comment by myfear** [comment]
I do see the same with: quarkus.hibernate-orm.schema-management.strategy=drop-and-create

**Comment by angelozerr** [comment]
Indeed tooling have some limitation (when property comes from deployment JARs), but it seems Quarkus provides (or will provide) those metadata in JAR. I need to explore that.

**Comment by angelozerr** [comment]
It should be fixed now.

**Comment by gian1200** [comment]
It still shows the warnings:

- Img 1:

  <img width="829" height="134" alt="Image" src="https://github.com/user-attachments/assets/3e8b8bea-7112-4a77-833a-199fbd320bf6" />

- Img 2:

  <img width="803" height="172" alt="Image" src="https://github.com/user-attachments/assets/5329f547-e5bd-40cf-9b70-3b362a5bc579" />



#### ENV:

```
Version: 1.106.3 (user setup)
Commit: bf9252a2fb45be6893dd8870c0bf37e2e1766d61
Date: 2025-11-25T22:28:18.024Z
Electron: 37.7.0
ElectronBuildId: 12781156
Chromium: 138.0.7204.251
Node.js: 22.20.0
V8: 13.8.258.32-electron.0
OS: Windows_NT x64 10.0.26200
```

```
Identifier: redhat.vscode-quarkus
Version: 1.21.0
```

## Update

I just realized that `v1.21.1` (which redirects to `1.22.0`) is referenced (but is still not published). Will wait for it to test it again

**Comment by angelozerr** [comment]
@gian1200 please be patient, we have some trouble to create the release. I will ping you when it will be available.

**Comment by angelozerr** [comment]
@gian1200 and please note that you will need to install vscode microprofile.

**Comment by gian1200** [comment]
Yes, I already have it. I believe it is automatically installed/enabled when using vscode-quarkus because it has a dependency on it.

I also have automatic updates enabled, so I should be all good!

Thanks for the reminder, though 👍🏻.

**Comment by angelozerr** [comment]
@gian1200 please update vscode-quarkus and give me feedback.

**Comment by gian1200** [comment]
Hello. Thanks for the heads up.

I tested it and it "kinda works":

1. ✅ It no longer shows a warning on some of the properties
2. Not sure if the suggested options are the ones expected

    <img width="617" height="133" alt="Image" src="https://github.com/user-attachments/assets/83757633-2f65-49c6-bd6e-aa30151393f7" />

3. Others are still flagged with warning (+ same comment as point 2)

    `quarkus.kubernetes.env.configmaps`
    `quarkus.kubernetes.env.secrets`
    `quarkus.kubernetes.env.mapping.VARIABLE.from-configmap`
    `quarkus.kubernetes.env.mapping.VARIABLE.from-secret`
    `quarkus.kubernetes.env.mapping.VAR".with-key`

    Examples:

    <img width="781" height="157" alt="Image" src="https://github.com/user-attachments/assets/e29a4d82-88f9-4db2-9692-37f02cc41fcb" />

    <img width="941" height="136" alt="Image" src="https://github.com/user-attachments/assets/3d7a3786-5438-4b57-8075-43843d501ad9" />

    <img width="1235" height="166" alt="Image" src="https://github.com/user-attachments/assets/d3300bdf-0f3f-4010-8dcd-2ef41810b441" />
    
    <img width="1037" height="108" alt="Image" src="https://github.com/user-attachments/assets/06bdecef-ab39-4ac1-afb3-70934a23d6cf" />

4. Caffeine properties have partial support (not sure if this is a separate issue)

    <img width="520" height="154" alt="Image" src="https://github.com/user-attachments/assets/8e571224-ed8c-49ce-ae34-803be10e5eca" />

    <img width="974" height="151" alt="Image" src="https://github.com/user-attachments/assets/6db7853b-e414-4e0c-b252-f2ecbbde9a64" />

**Comment by angelozerr** [comment]
> Hello. Thanks for the heads up.
> 
> I tested it and it "kinda works":
> 
> 1. ✅ It no longer shows a warning on some of the properties
> 2. Not sure if the suggested options are the ones expected
> 
>     <img width="617" height="133" alt="Image" src="https://github.com/user-attachments/assets/83757633-2f65-49c6-bd6e-aa30151393f7" />
> 
> 3. Others are still flagged with warning (+ same comment as point 2)
> 
>     `quarkus.kubernetes.env.configmaps`
>     `quarkus.kubernetes.env.secrets`
>     `quarkus.kubernetes.env.mapping.VARIABLE.from-configmap`
>     `quarkus.kubernetes.env.mapping.VARIABLE.from-secret`
>     `quarkus.kubernetes.env.mapping.VAR".with-key`
> 
>     Examples:
> 
>     <img width="781" height="157" alt="Image" src="https://github.com/user-attachments/assets/e29a4d82-88f9-4db2-9692-37f02cc41fcb" />
> 
>     <img width="941" height="136" alt="Image" src="https://github.com/user-attachments/assets/3d7a3786-5438-4b57-8075-43843d501ad9" />
> 
>     <img width="1235" height="166" alt="Image" src="https://github.com/user-attachments/assets/d3300bdf-0f3f-4010-8dcd-2ef41810b441" />
>     
>     <img width="1037" height="108" alt="Image" src="https://github.com/user-attachments/assets/06bdecef-ab39-4ac1-afb3-70934a23d6cf" />
> 
> 4. Caffeine properties have partial support (not sure if this is a separate issue)
> 
>     <img width="520" height="154" alt="Image" src="https://github.com/user-attachments/assets/8e571224-ed8c-49ce-ae34-803be10e5eca" />
> 
>     <img width="974" height="151" alt="Image" src="https://github.com/user-attachments/assets/6db7853b-e414-4e0c-b252-f2ecbbde9a64" />

@gian1200 thanks for your feedback. I need to find time to understand what it happens.

**Comment by angelozerr** [comment]
@gian1200 could you install pre-release, it should work better:

<img width="1482" height="679" alt="Image" src="https://github.com/user-attachments/assets/e67ea9ca-b4cb-4ec9-ae27-b5f20bd8110e" />

**Comment by gian1200** [comment]
Hello again.


Yes, it does work better. However, I'm finding some "interesting" scenarios which I'm not sure if they are "working as expected" or not.


1. E.g.: if you have `quarkus.kubernetes.env.mapping.VAR_NAME_ONE.from-configmap`, when autocompleting in the "quarkus.kubernetes.env.mapping" section, it works fine. However, if doing the same inside the "from-configmap" section, it doesn't.
    Given that there is a `.{*}.`, I expected for it to support any string between the dots. This happens with multiple properties

    <img width="659" height="49" alt="Image" src="https://github.com/user-attachments/assets/61654bc0-1991-44c4-a63c-acc2800c6cc6" />


    <img width="623" height="58" alt="Image" src="https://github.com/user-attachments/assets/5d7a11ce-d38b-4483-a432-2f40d8f27e64" />

2. There are some duplicate suggestions:

    <img width="262" height="96" alt="Image" src="https://github.com/user-attachments/assets/e6c523f2-a2ea-4c6a-8875-25d9ccc12b5d" />


    <img width="209" height="84" alt="Image" src="https://github.com/user-attachments/assets/acc31951-359f-4edb-b4c7-f84d1e7974a7" />

    <img width="206" height="38" alt="Image" src="https://github.com/user-attachments/assets/604e7668-3d4f-42bc-a29f-ecdd08944752" />

3. Even though, some properties support multiple values within the property name, is it expected to not show the "default" suggestion (without asterisk)? In the following example, I expected to also see `quarkus.datasource.db-kind` as the first suggestion (or all the possibilities without asterisk).

    <img width="459" height="55" alt="Image" src="https://github.com/user-attachments/assets/254a2933-7cad-4564-9543-75e57524f1c6" />

4.  Is it expected to have `[*]` in the name? Given that the property name remains unchanged, I expected to see `quarkus.kubernetes.env.configmaps` as suggestion. The property type already says that is a List of strings

    <img width="517" height="54" alt="Image" src="https://github.com/user-attachments/assets/bc98b428-d160-496f-b47a-816d5624af49" />


    <img width="314" height="171" alt="Image" src="https://github.com/user-attachments/assets/d6c045b2-8733-4066-b875-126ae4d0c9d1" />

5. Not sure if this is a regression or a new feature request (let me know if you want me to create a new issue): There are no suggestions when there is a profile:

    <img width="390" height="119" alt="Image" src="https://github.com/user-attachments/assets/3e41bfff-bb5b-46f3-8481-1eb87f40d615" />

**Comment by angelozerr** [comment]
@gian1200 thanks again for your patience and for your reported issue.

Is it possible please to create an issue per problem. Thanks!

I close this issue since a lot of thing has been fixed.

**Comment by angelozerr** [comment]
> Is it expected to have [*] in the name? Given that the property name remains unchanged, I expected to see quarkus.kubernetes.env.configmaps as suggestion. The property type already says that is a List of strings

fixed with https://github.com/eclipse-lsp4mp/lsp4mp/pull/538

**Comment by gian1200** [comment]
Good morning!

> please to create an issue per problem

Done!

**Comment by angelozerr** [comment]
Thanks so much @gian1200 ! I am working on your issues.
